# Generated by Django 3.1.6 on 2021-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_info',
            name='conv_direction',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='conv_max_length_dual',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='conv_max_length_single',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='conv_max_width_dual',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='conv_max_width_single',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='cpu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='feederbase_tape',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='feederbase_tray',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='fid_cam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='fixed_cam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='flying_cam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='latest_cali_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_10',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_11',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_12',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_13',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_14',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_15',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_6',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_7',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_8',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='option_9',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='ver_basic_it',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='ver_t_it_basic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qr_info',
            name='ver_t_it_full',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
