# Generated by Django 3.1.6 on 2021-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='col1',
            field=models.IntegerField(default=1),
        ),
    ]
