# Generated by Django 3.1.6 on 2021-02-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_col1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='col2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col3',
            field=models.IntegerField(default=1),
        ),
    ]
