# Generated by Django 3.1.6 on 2021-02-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_bookmark_col1_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='col10_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col11_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col12_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col13_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col14_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col15_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col16_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col17_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col18_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col19_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col20',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col20_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col21_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col22_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col23_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col24_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col25_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col26_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col27_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col28_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col29_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col2_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col3_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col4_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col5_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col6_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col7_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col8_txt',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='col9_txt',
            field=models.CharField(default='', max_length=150),
        ),
    ]
