# Generated by Django 3.1.6 on 2021-02-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_auto_20210203_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='col1_txt',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='col2_txt',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='col3_txt',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='col4_txt',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
