# Generated by Django 3.1.6 on 2021-02-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_auto_20210203_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='col1_txt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='col2_txt',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
