# Generated by Django 3.1.6 on 2021-02-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_auto_20210203_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='col3_txt',
            field=models.CharField(default='  ', max_length=150, null=True),
        ),
    ]
