# Generated by Django 3.1.6 on 2021-02-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_auto_20210203_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='col3_txt',
            field=models.CharField(default='N/A', max_length=150, null=True),
        ),
    ]
