# Generated by Django 3.1.6 on 2021-02-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0013_auto_20210203_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='confirm_bs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='confirm_news',
            field=models.IntegerField(default=0),
        ),
    ]
