# Generated by Django 3.1.6 on 2021-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0014_auto_20210203_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bs_opinion',
            field=models.TextField(default='BS 프로그램에 기준한 점검결과 특이사항이 없습니다.', null=True),
        ),
    ]
