# Generated by Django 3.1.6 on 2021-02-03 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0016_auto_20210203_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
