# Generated by Django 3.1.6 on 2021-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0017_auto_20210203_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='inspector',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
