# Generated by Django 3.1.6 on 2021-02-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0018_bookmark_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='manager_opinion',
            field=models.TextField(default='기타 의견 및 요청항목이 없습니다.', null=True),
        ),
    ]
