# Generated by Django 3.1.6 on 2021-02-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0019_bookmark_manager_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('order', models.IntegerField(null=True)),
                ('remarks_1', models.CharField(max_length=50, null=True)),
                ('remarks_2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmark.client'),
        ),
    ]
