# Generated by Django 3.1.6 on 2021-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0020_auto_20210221_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
