# Generated by Django 3.1.6 on 2021-02-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0024_bookmark_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created']},
        ),
    ]
