# Generated by Django 3.1.6 on 2021-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0025_auto_20210223_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='part1_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='part1_img',
            field=models.ImageField(default='photos/no_image.png', null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='machine',
            name='part1_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='part1_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
