# Generated by Django 3.1.6 on 2021-02-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0029_auto_20210224_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='part3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part3', to='bookmark.consumed', to_field='part_code'),
        ),
        migrations.AddField(
            model_name='machine',
            name='part3_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='part4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part4', to='bookmark.consumed', to_field='part_code'),
        ),
        migrations.AddField(
            model_name='machine',
            name='part4_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='part5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part5', to='bookmark.consumed', to_field='part_code'),
        ),
        migrations.AddField(
            model_name='machine',
            name='part5_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='part6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part6', to='bookmark.consumed', to_field='part_code'),
        ),
        migrations.AddField(
            model_name='machine',
            name='part6_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='part7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part7', to='bookmark.consumed', to_field='part_code'),
        ),
        migrations.AddField(
            model_name='machine',
            name='part7_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='part8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part8', to='bookmark.consumed', to_field='part_code'),
        ),
        migrations.AddField(
            model_name='machine',
            name='part8_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='part9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part9', to='bookmark.consumed', to_field='part_code'),
        ),
        migrations.AddField(
            model_name='machine',
            name='part9_qty',
            field=models.IntegerField(null=True),
        ),
    ]
