# Generated by Django 3.1.6 on 2021-02-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0030_auto_20210224_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumed',
            name='part_desc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
