# Generated by Django 3.1.6 on 2021-02-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0032_bookmark_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='visibility',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='available_display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
    ]
