# Generated by Django 3.1.6 on 2021-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0033_auto_20210225_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='visibility',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
