# Generated by Django 3.1.6 on 2021-02-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0034_bookmark_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='available_display',
        ),
    ]
