# Generated by Django 3.1.6 on 2021-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0035_remove_bookmark_available_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='available_display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
    ]
