# Generated by Django 3.1.6 on 2021-02-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0037_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='bookmark.client'),
        ),
    ]
