# Generated by Django 3.1.6 on 2021-02-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0039_auto_20210227_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['client', 'line', 'order', '-created']},
        ),
    ]
