# Generated by Django 3.1.6 on 2021-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0040_auto_20210227_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='line',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
