# Generated by Django 3.1.6 on 2021-02-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0041_auto_20210227_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, null=True)),
                ('item', models.CharField(default='-', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(default='photos/no_image.png', null=True, upload_to='static/img/report')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_for_clients', to='bookmark.client')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_for_items', to='bookmark.reportitem')),
            ],
        ),
    ]
