# Generated by Django 3.1.6 on 2021-02-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0042_report_reportitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='num',
            field=models.IntegerField(default=1, null=True, unique=True),
        ),
    ]
