# Generated by Django 3.1.6 on 2021-02-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0043_auto_20210227_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportitem',
            options={'ordering': ['num']},
        ),
    ]
