# Generated by Django 3.1.6 on 2021-02-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0044_auto_20210227_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='target_goods',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='target_goods_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100000000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='target_goods_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
