# Generated by Django 3.1.6 on 2021-02-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0045_auto_20210227_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_goods',
            field=models.CharField(default='-', max_length=50, null=True),
        ),
    ]
