# Generated by Django 3.1.6 on 2021-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0047_auto_20210227_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mini_title',
            field=models.CharField(default='-', max_length=50, null=True),
        ),
    ]
