# Generated by Django 3.1.6 on 2021-02-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0049_auto_20210228_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='img2_alt',
            field=models.CharField(default='caption2', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='img3_alt',
            field=models.CharField(default='caption3', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='img_alt',
            field=models.CharField(default='caption1', max_length=50, null=True),
        ),
    ]
