# Generated by Django 3.1.6 on 2021-02-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0050_auto_20210228_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumed',
            name='part_img',
            field=models.ImageField(default='photos/no_image.png', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='img',
            field=models.ImageField(default='photos/no_image.png', null=True, upload_to='img/report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='img2',
            field=models.ImageField(default='photos/no_image.png', null=True, upload_to='img/report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='img3',
            field=models.ImageField(default='photos/no_image.png', null=True, upload_to='img/report'),
        ),
    ]
