# Generated by Django 3.1.6 on 2021-02-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0051_auto_20210228_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='mini_title',
        ),
        migrations.AddField(
            model_name='report',
            name='mini_title_or_main_product',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='desc',
            field=models.TextField(default='-', null=True),
        ),
    ]
