# Generated by Django 3.1.6 on 2021-02-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('position_other', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
