# Generated by Django 3.1.6 on 2021-02-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='q2_after_service',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_after_service_other',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_air',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_conveyor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_feederbase',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_head_anc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_illumination',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_overall',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_sw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_trust',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_trust_other',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q2_xy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='position_other',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
