# Generated by Django 3.1.6 on 2021-02-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210217_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='q3_1_main_concern',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q3_2_1_future_interest_smart_erp',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q3_2_2_future_interest_factory_automation',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q3_2_3_future_interest_remote_support',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q3_2_4_future_interest_systematical_training',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q3_2_5_future_interest_other',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='q3_2_5_other',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
