# Generated by Django 3.1.6 on 2021-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210220_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='q3_3_recommend_to_other',
            field=models.IntegerField(null=True),
        ),
    ]
