# Generated by Django 3.1.6 on 2021-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_survey_q3_3_recommend_to_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='manager_opinion',
            field=models.TextField(default='기타 의견 및 요청항목이 없습니다.', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='policy_agreement',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
